### ISSUE TITLE
Roadmap: towards v0.4.0

### ISSUE THREAD

**Issue by PerezHz** [PerezHz/TaylorIntegration.jl#32]
Hi! I'm opening this issue as a to-do list of current WIP that we would like to get done for the upcoming releases of TaylorIntegration.jl. If you think something should be modified or added, feel free to comment. As always, feedback is very welcome!

- [x] Add documentation
- [x] Add JuliaDiffEq common interface bindings for (#19)
- [x] Migrate tests from `FactCheck` to `Base.Test`; separate tests into several files (see [#33])
- [x] Solve other pending open issues (~#20~, ~#27~)

@lbenet @blas-ko

EDIT: Updated the PR where the tests are being migrated.
EDIT: Updated title and first comment of this issue, so that it reflects current development efforts.
EDIT: Updated issue title
EDIT: Reviewing, testing, and merging of #31 will be done after v0.4.0 tagging
EDIT: documentation was added in #57; update to-do list accordingly
EDIT: After v0.4.0 release, #20 was closed

**Comment by lbenet** [comment]
Just a note about the second item of the list; #31 will work in Julia 0.6 only, because changes in TaylorSeries already use the 0.6 syntax.

**Comment by lbenet** [comment]
Related to the migration to Julia 0.6, see https://juliacomputing.com/blog/2017/08/17/femtocleaner.html . Perhaps it is a good idea to compare the differences...

**Comment by lbenet** [comment]
Another comment: #20 would be solved by #31, is the macro is used.

**Comment by PerezHz** [comment]
@lbenet just updated the title of this issue and updated the to-do list

**Comment by lbenet** [comment]
I am in favor of releasing v0.4.0 once #62 is merged. 

While we haven't completely solved #20, there are ways to get around this; see [this comment](https://github.com/PerezHz/TaylorIntegration.jl/issues/20#issuecomment-456444995).

**Comment by PerezHz** [comment]
@lbenet v0.4.0 was just released (see JuliaLang/METADATA.jl#20778) and #20 has been closed. Accordingly, I will also close this issue.
